# Site settings
title: "wangsp"
bye_message: "Copyright © 2019 Wang sp"
baseurl: "/note/"
url: "https://wangspx.github.io"
disqus: wangsp

# Header settings
nick: "Wangsp"
mail:
    domain: "wangspx"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "wangsp"
blog:
    server: "wangsp.github.io/note"
    nick: "wangsp"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
