# Site settings
title: "Wangsp"
bye_message: "Thx!"
baseurl: "/note/"
url: "https://wangspx.github.io"
disqus: Wangsp

# Header settings
nick: "Wangsp"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "Wangsp"
blog:
    server: "wordpress.com"
    nick: "Wangsp"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
